/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f7d48fbf-febe-4ba4-acbb-e4a1ecefeb83",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UuEBOqc6L",
    "aws_user_pools_web_client_id": "uehobkhu95v3giagdl8cat8kc",
    "oauth": {}
};


export default awsmobile;
